# Generated by Django 3.0.8 on 2020-07-30 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='price',
        ),
        migrations.AddField(
            model_name='listings',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
