# Generated by Django 3.0.8 on 2020-07-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200729_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.CharField(default='NULL', max_length=64),
        ),
    ]
