# Generated by Django 3.0.8 on 2020-07-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200730_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=64)),
                ('price', models.IntegerField(default='0')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
