# Generated by Django 3.0.8 on 2020-08-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='startingbid',
        ),
    ]
