# Generated by Django 3.0.8 on 2020-08-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200731_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlistitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(default='NULL', max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='bids',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AddField(
            model_name='bid',
            name='name',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AddField(
            model_name='comment',
            name='buyer',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment', to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='listing',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default='None', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingbid',
            field=models.IntegerField(default=0),
        ),
    ]
