# Generated by Django 3.0.8 on 2020-08-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200827_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestbid',
            field=models.IntegerField(default = 0),
        ),
    ]
